config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :homeworks

   root 'home#index'

    resources :courses
    resources :teachers do
      get :community, on: :collection #esta parte me sirve para crear una vista igual al listado de profesores 
    end
    resources :homeworks
    resources :students

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_and_belongs_to_many :teachers
	has_many :homeworks
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/homework.rb
class Homework < ActiveRecord::Base
	belongs_to :course
	belongs_to :teacher
end

app/models/student.rb
class Student < ActiveRecord::Base
	
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_and_belongs_to_many :courses
	has_many :homeworks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@course = Course.all
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(course_params)
		@course.save
		redirect_to courses_path
		#puts COURSE_params
	end

	def show
		@course = Course.find(params[:id])
		
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])
		@course.update(course_params)
		redirect_to courses_path #si coloco course_path, se ira a la vista show, pero como no la necesito lo coloco en plural para que se me vaya a la vistad de todas las torres
	end

	def destroy
		@course = Course.find(params[:id])
		@course.destroy
		redirect_to courses_path
	end
	
	def course_params
		params.require(:course).permit(:name, :code)
	end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:message, :score)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@course = Course.all
		@teacher = Teacher.all
	end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]

  # GET /homeworks
  # GET /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = Homework.new(homework_params)

    respond_to do |format|
      if @homework.save
        format.html { redirect_to @homework, notice: 'Homework was successfully created.' }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_params
      params.require(:homework).permit(:wording, :date)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@student = Student.all
	end

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)
		@student.save
		redirect_to students_path
		#puts student_params
	end

	
	def show
		@student = Student.find(params[:id])
		
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])
		@student.update(student_params)
		redirect_to students_path #si coloco student_path, se ira a la vista show, pero como no la necesito lo coloco en plural para que se me vaya a la vistad de todas las torres
	end

	def destroy
		@student = Student.find(params[:id])
		@student.destroy
		redirect_to students_path
	end
	
	def student_params
		params.require(:student).permit(:name, :lastname, :email, :document, :course)
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	def index
		@teacher = Teacher.all
	end

	def new
		@teacher = Teacher.new
	end

	def create
		@teacher = Teacher.new(teacher_params)
		@teacher.save
		redirect_to teachers_path
		#puts teacher_params
	end

	def community #esto me sirve para agregar una vista igual a la lista de profesores sin que se pueda editar (le borro la parte de editar y eliminar y de resto la copio igual) (ver codigo en el archivo routes en la parte resources)
		@teacher = Teacher.all
		
	end

	def show
		@teacher = Teacher.find(params[:id])
		
	end

	def edit
		@teacher = Teacher.find(params[:id])
	end

	def update
		@teacher = Teacher.find(params[:id])
		@teacher.update(teacher_params)
		redirect_to teachers_path #si coloco teacher_path, se ira a la vista show, pero como no la necesito lo coloco en plural para que se me vaya a la vistad de todas las torres
	end

	def destroy
		@teacher = Teacher.find(params[:id])
		@teacher.destroy
		redirect_to teachers_path
	end
	
	def teacher_params
		params.require(:teacher).permit(:name, :lastname, :document, :course, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/courses/edit.html.erb
<h1>Actualizar Asignatura</h1>

<%= form_for @course do |f| %>
<%= link_to "ver todas", course_path %>

<p>
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_area :name %>
</p>

 <p>
    <%= f.label :code, "Codigo" %><br>
    <%= f.text_area :code %>
 </p>

 <p>
    <%= f.submit %>
 </p>
<% end %>

app/views/courses/index.html.erb
<h1>Lista de Asignaturas</h1>

<ul>
	<% @course.each do |course| %>

		<li>
		<p>Nombre de la asignatura: <%= course.name %></p>
		<p>Codigo: <%= course.code %></p>

	    <%= link_to"Ver detalle", course_path(course)%> 
		<%= link_to"editar", edit_course_path(course)%> 
		<%= link_to"eliminar", course_path(course), method: :delete, data: {confirm: "estas seguro?"} %>
		</li>
	
	<% end %>
</ul>

<%= link_to "Agregar Asignatura", new_course_path %>

app/views/courses/new.html.erb
<h1>Introducir Asignatura</h1>

<%= form_for @course do |f| %>

  <p>
    <%= f.label :name, "Nombre de la asignatura" %><br>
    <%= f.text_area :name %>
  </p>

  <p>
    <%= f.label :code, "Codigo" %><br>
    <%= f.text_area :code %>
  </p>

  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/courses/show.html.erb
<h1>Asignatura</h1>


<% @course.apartments.each do |apartamento| %>

<%= link_to apartamento.numero, apartamento %>

<%end%>

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Respuestas a tareas</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.message %></td>
        <td><%= feedback.score %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @feedback.message %>
</p>

<p>
  <strong>Score:</strong>
  <%= @feedback.score %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>

app/views/home/index.html.erb
<h1>Institucion Educativa XXX</h1>

<ul>
	<li><%= link_to"Ingresar como profesor", teachers_path%></li>
	<li><%= link_to"Ingresar como estudiante", courses_path%></li> 
	<li><%= link_to"Visitante", courses_path%></li> 
</ul>

app/views/homeworks/_form.html.erb
<%= form_for(@homework) do |f| %>
  <% if @homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
      <% @homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wording %><br>
    <%= f.text_field :wording %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homeworks/edit.html.erb
<h1>Editing Homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Homeworks</h1>

<table>
  <thead>
    <tr>
      <th>Wording</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.wording %></td>
        <td><%= homework.date %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

app/views/homeworks/new.html.erb
<h1>New Homework</h1>

<%= render 'form' %>

<%= link_to 'Back', homeworks_path %>

app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wording:</strong>
  <%= @homework.wording %>
</p>

<p>
  <strong>Date:</strong>
  <%= @homework.date %>
</p>

<%= link_to 'Edit', edit_homework_path(@homework) %> |
<%= link_to 'Back', homeworks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colegio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/edit.html.erb
<h1>Actualizar Estudiante</h1>

<%= form_for @student do |f| %>
<%= link_to "ver todos", students_path %>

<p>
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_area :name %>
</p>

 <p>
    <%= f.label :lastname, "Apellido" %><br>
    <%= f.text_area :lastname %>
</p>

<p>
    <%= f.label :document, "Documento de identidad" %><br>
    <%= f.text_area :document %>
</p>

<p>
    <%= f.label :course, "Asignatura que cursa" %><br>
    <%= f.text_area :course %>
</p>

<p>
    <%= f.label :email, "correo electronico" %><br>
    <%= f.text_area :email %>
</p>

<p>
    <%= f.submit %>
</p>
<% end %>

app/views/students/index.html.erb
<h1>Lista de Estudiantes</h1>

<ul>
	<% @student.each do |student| %>

		<li>
		<p>Nombre: <%= student.name %></p>
		<p>Apellidos: <%= student.lastname %></p>
		<p>Documento de identidad: <%= student.document %></p>
		<p>Asignaturas que cursa: <%= student.course %></p>
		<p>email: <%= student.email %></p>

	    <%= link_to"Ver detalle", student_path(student)%> 
		<%= link_to"editar", edit_student_path(student)%> 
		<%= link_to"eliminar", student_path(student), method: :delete, data: {confirm: "estas seguro?"} %>
		</li>
	
	<% end %>
</ul>

<%= link_to "Ingresar nuevo estudiante", new_student_path %>

app/views/students/new.html.erb
<h1>Agregar Estudiante</h1>

<%= form_for @student do |f| %>

  <p>
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_area :name %>
  </p>

  <p>
    <%= f.label :lastname, "Apellido" %><br>
    <%= f.text_area :lastname %>
  </p>
  <p>
    <%= f.label :document, "Documento de identidad" %><br>
    <%= f.text_area :document %>
  </p>
  <p>
    <%= f.label :course, "Asignaturas que cursa" %><br>
    <%= f.text_area :course %>
  </p>
  <p>
    <%= f.label :email, "Correo electronico" %><br>
    <%= f.text_area :email %>
  </p>

  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/teachers/community.html.erb
<h1>Lista global de profesores</h1> <!--esto me sirve para agregar una vista igual a la lista de profesores sin que se pueda editar (le borro la parte de editar y eliminar y de resto la copio igual).IMPORTANTE ver el codigo en el archivo routes en la parte resources-->
<ul>
	<% @teacher.each do |teacher| %>

		<li>
		<p>Nombre: <%= teacher.name %></p>
		<p>Apellidos: <%= teacher.lastname %></p>
		<p>Documento de identidad: <%= teacher.document %></p>
		<p>Asignatura: <%= teacher.course %></p>
		<p>email: <%= teacher.email %></p>

	    </li>
	
	<% end %>
</ul>

<%= link_to "Ingresar nuevo profesor", new_teacher_path %>

app/views/teachers/edit.html.erb
<h1>Actualizar Profesor</h1>

<%= form_for @teacher do |f| %>
<%= link_to "ver todos", teachers_path %>

<p>
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_area :name %>
</p>

 <p>
    <%= f.label :lastname, "Apellido" %><br>
    <%= f.text_area :lastname %>
</p>

<p>
    <%= f.label :document, "Documento de identidad" %><br>
    <%= f.text_area :document %>
</p>

<p>
    <%= f.label :course, "Asignatura" %><br>
    <%= f.text_area :course %>
</p>

<p>
    <%= f.label :email, "correo electronico" %><br>
    <%= f.text_area :email %>
</p>

<p>
    <%= f.submit %>
</p>
<% end %>

app/views/teachers/index.html.erb
<h1>Lista de Profesores</h1>

<ul>
	<% @teacher.each do |teacher| %>

		<li>
		<p>Nombre: <%= teacher.name %></p>
		<p>Apellidos: <%= teacher.lastname %></p>
		<p>Documento de identidad: <%= teacher.document %></p>
		<p>Asignatura: <%= teacher.course %></p>
		<p>email: <%= teacher.email %></p>

	    <%= link_to"Ver detalle", teacher_path(teacher)%> 
		<%= link_to"editar", edit_teacher_path(teacher)%> 
		<%= link_to"eliminar", teacher_path(teacher), method: :delete, data: {confirm: "estas seguro?"} %>
		</li>
	
	<% end %>
</ul>

<%= link_to "Ingresar nuevo profesor", new_teacher_path %>

app/views/teachers/new.html.erb
<h1>Agregar profesor</h1>

<%= form_for @teacher do |f| %>

  <p>
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_area :name %>
  </p>

  <p>
    <%= f.label :lastname, "Apellido" %><br>
    <%= f.text_area :lastname %>
  </p>
  <p>
    <%= f.label :document, "Docuemento de identidad" %><br>
    <%= f.text_area :document %>
  </p>
  <p>
    <%= f.label :course, "Asignatura" %><br>
    <%= f.text_area :course %>
  </p>
  <p>
    <%= f.label :email, "Correo electronico" %><br>
    <%= f.text_area :email %>
  </p>

  
  <p>
    <%= f.submit %>
  </p>
<% end %>